#!/bin/bash
# adapted from http://www.haskell.org/haskellwiki/How_to_profile_a_Haskell_program

set -ex

PROG=demo
VIEW=gv

runhaskell Setup configure --enable-executable-profiling --user --ghc-options='-auto'
runhaskell Setup.lhs build
dist/build/${PROG}/${PROG} +RTS -sstderr -p -hc
hp2ps ${PROG}.hp
#${VIEW} ${PROG}.ps
#cat ${PROG}.summary
